### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by Rjected**

### CODE REVIEW

**Comment by stepancheg** [comment]
Why?

**Comment by Rjected** [comment]
> Why?

This PR does not have any concrete improvements other than cutting down slightly on the number of sub dependencies.
Example: 109 items for this branch `cargo clean; cargo check --workspace --all-features`, 116 for main

I'm planning to use this in one of my projects and this seemed like a good way to start onboarding myself onto the codebase.

**Comment by stepancheg** [comment]
This PR cannot be easily merged as is, because versions of dependencies should be in sync with our internal monorepository versions.

Generally we try to use latest stable versions, and while this PR upgrades some dependencies, some work might be needed to make sure internal versions are compatible with these versions.

So unless there's some specific problem with current dep versions, I'm hesitant to merge this PR.

**Comment by Rjected** [comment]
> This PR cannot be easily merged as is, because versions of dependencies should be in sync with our internal monorepository versions.
> 
> Generally we try to use latest stable versions, and while this PR upgrades some dependencies, some work might be needed to make sure internal versions are compatible with these versions.
> 
> So unless there's some specific problem with current dep versions, I'm hesitant to merge this PR.

ah I see, makes sense. I'll close this PR then since they aren't required for my use of allocative either afaict.

**Pull request closed without merging**
